- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
   - name: Import VPC variables
     include_vars: vars/vpc_setup

   - name: Create DevOps VPC
     ec2_vpc_net:
       name: "{{vpc_name}}"
       cidr_block: "{{vpcCidr}}"
       region: "{{region}}"
       dns_support: yes
       dns_hostnames: yes
       tenancy: default
       state: "{{state}}"
     register: vpc_out

   - name: Creating public subnet1
     ec2_vpc_subnet:
         vpc_id: "{{vpc_out.vpc.id}}"
         region: "{{region}}"
         az: "{{zone1}}"
         state: "{{state}}"
         cidr: "{{PubSub1}}"
         map_public: yes
         tags:
           Name: devops-publicsubnet-1
     register: pubsub1_out

   - name: Creating public subnet2
     ec2_vpc_subnet:
              vpc_id: "{{vpc_out.vpc.id}}"
              region: "{{region}}"
              az: "{{zone2}}"
              state: "{{state}}"
              cidr: "{{PubSub2}}"
              map_public: yes
              tags:
                Name: devops-publicsubnet-2
     register: pubsub2_out

   - name: Creating public subnet3
     ec2_vpc_subnet:
              vpc_id: "{{vpc_out.vpc.id}}"
              region: "{{region}}"
              az: "{{zone3}}"
              state: "{{state}}"
              cidr: "{{PubSub3}}"
              map_public: yes
              tags:
                Name: devops-publicsubnet-3
     register: pubsub3_out

   - name: Creating private subnet1
     ec2_vpc_subnet:
              vpc_id: "{{vpc_out.vpc.id}}"
              region: "{{region}}"
              az: "{{zone1}}"
              state: "{{state}}"
              cidr: "{{PrivSub1}}"
              map_public: yes
              tags:
                Name: devops-privatesubnet-1
     register: privsub1_out

   - name: Creating private subnet2
     ec2_vpc_subnet:
                   vpc_id: "{{vpc_out.vpc.id}}"
                   region: "{{region}}"
                   az: "{{zone2}}"
                   state: "{{state}}"
                   cidr: "{{PrivSub2}}"
                   map_public: yes
                   tags:
                     Name: devops-privatesubnet-2
     register: privsub2_out


   - name: Creating private subnet3
     ec2_vpc_subnet:
                   vpc_id: "{{vpc_out.vpc.id}}"
                   region: "{{region}}"
                   az: "{{zone3}}"
                   state: "{{state}}"
                   cidr: "{{PrivSub3}}"
                   map_public: yes
                   tags:
                     Name: devops-privatesubnet-3
     register: privsub3_out

   - name: Creating IGW
     ec2_vpc_igw:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        tags:
          Name: devops-IGW
     register: IGW_Out








